### ISSUE TITLE
allow to pass in branch name

### ISSUE THREAD

**Issue by kishore881** [NodeSecure/i18n#115]
some repos have master as the default branch instead of main, for those repos, the download fn, downloads a zip file with content 404 Not Found, throwing errors when trying to extract their content.

Example: @NodeSecure/scanner, @NodeSecure/cli both have master as the default branch

**Comment by kishore881** [comment]
just noticed it is actually feasible via download options

**Comment by fraxken** [comment]
Yes scanner and CLI are old repository (created before main was the default on Github)
