### ISSUE TITLE
Creating a web documentation to check keys and translation

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/i18n#15]
The goal of this task is to create/generate a **static** webpage to be able to check our keys and translation (in all languages) from a github URL.

We need a script to dynamically generate the static page with a template engine like [zup](https://github.com/mscdex/zup#readme) (a fairly simple and fast template engine we often use). The static page will be hosted with [Github pages](https://pages.github.com/).

This documentation will help us when we have to work on the CLI or other components where you have to search for i18n keys. Because the only way is to open the code itself.

**Comment by zwOk9** [comment]
good evening, 
when you say a github url it is a github page?

**Comment by fraxken** [comment]
Yes i mean a static HTML github page (so we don't have to host it or anything).

**Comment by zwOk9** [comment]
I'm trying to take care of it this weekend

**Comment by im-codebreaker** [comment]
You can find **i18n** UI just below.
If you need more details just feel free to message me.

![NodeSecure i18n - CLI](https://user-images.githubusercontent.com/53506859/164971612-3c2fb10b-c64d-4c6f-a60e-bbf2d0ece5de.jpg)
![NodeSecure i18n - DEPWALKER](https://user-images.githubusercontent.com/53506859/164971619-bc09dc5c-85b7-4fcc-9cb0-a3960e682974.jpg)
![NodeSecure i18n - UI](https://user-images.githubusercontent.com/53506859/164971623-d4a8eeb4-8526-4591-b948-8d6698361b3a.jpg)
![NodeSecure i18n - Warning](https://user-images.githubusercontent.com/53506859/164971634-47794658-f5cf-4311-b7d1-dd06fc435775.jpg)

**Comment by im-codebreaker** [comment]
Hello 👋 ! 

I take care of this issue

**Comment by fraxken** [comment]
@all-contributors please add @im-codebreaker for code, doc, design
