### ISSUE TITLE
Add new API to dynamically extend language tokens

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/i18n#47]
The goal of the task is to refactor the API to allow dynamic extension of one or many languages:

```js
import * as i18n from "@nodesecure/i18n";

// Manually
i18n.extend("french", {});

// Synchronously read files (same format as the /languages dir)
i18n.extendFromSystemPath("./i18n");
```

> **Note** If the language doesn't exist it must be created under the hood

The idea behind this task is to move back **some** translations to their original projects.

**Comment by fabnguess** [comment]
Hello @fraxken , I would like to take this task. Should this API (setLocalLang) be refactored

**Comment by fraxken** [comment]
@fabnguess No, there is no expected breaking changes on current API. 

Also `setLocalLang` is to a set an active language, so there is relation with current task.

**Comment by fabnguess** [comment]
Sorry, I understood the subject, this is to add two new APIs namely (extend and extendFromSystemPath)?

**Comment by fraxken** [comment]
Yes
