### ISSUE TITLE
test: check compliance between .js and index.html

### ISSUE THREAD

**Issue by tony-go** [NodeSecure/i18n#66]
We currently have the exact string duplicate in HTML and Javascript files.

It could be nice to have a script (run on CI) to check that both strings are identical.

Something generic enough that we don't have to touch it anymore once it's ready. If we add new keys, this script/test case should embed them.

**Comment by fraxken** [comment]
Not sure if that's really useful since we can regenerate the whole documentation ^^

**Comment by tony-go** [comment]
> Not sure if that's really useful since we can regenerate the whole documentation ^^

So it's definitely not useful ^^
