### ISSUE TITLE
Add banner

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/i18n#67]
Add the i18n banner at the top of the README file like in [RC project](https://github.com/NodeSecure/rc)

![I18N_banner](https://user-images.githubusercontent.com/4438263/226019205-7d86a8d5-345f-416f-bc8d-c4aef6f12868.jpg)

**Comment by JasferI** [comment]
i wiil do this

**Comment by JasferI** [comment]
i will do this

**Comment by Ineslujan** [comment]
I do this if it's not already assigned

**Comment by fraxken** [comment]
@Ineslujan you can do it :)

**Comment by fraxken** [comment]
@allcontributors please add @Ineslujan for doc
